### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by igor-savin-ht** [7upcat/mobx-event-bus#1]
It would be very useful to have tests and, ideally, execute them with Travis.

**Comment by igor-savin-ht** [comment]
@7upcat Would you accept PR with tests?

**Comment by 7upcat** [comment]
Add  integration with Travis , tests  contribute welcomed also ： ）

**Comment by igor-savin-ht** [comment]
@7upcat Probably would be useful to keep issue open, until we add the tests :). Also maybe you could add write permissions for @kibertoad and @valtari1h? That would make it so much easier to contribute.
